class Config:
    valid_headers = [
        "item ark",
        "parent ark",
        "item status id",
        "item status",
        "object type",
        "file name",
        "item sequence",
        "duplicate",
        "delete in title",
        "thumbnail",
        "viewinghint",
        "text direction",
        "visibility",
        "iiif range",
        "type.typeofresource",
        "type.genre",
        "rights.copyrightstatus",
        "rights.statementlocal",
        "rights.servicescontact",
        "language",
        "coverage.geographic",
        "coverage.temporal",
        "subject",
        "alt id.local",
        "title",
        "name.creator",
        "alttitle.uniform",
        "relation.ispartof",
        "summary",
        "description.note",
        "date.creation",
        "date.normalized",
        "publisher.placeoforigin",
        "publisher.publishername",
        "name.subject",
        "name.photographer",
        "name.repository",
        "finding aid url",
        "opac url",
        "bucketeer state",
        "iiif access url",
        "iiif manifest url",
        "media.width",
        "media.height",
        "media.duration",
        "media.format",
        "waveform",
        "license",
    ]
    invalid_headers = []
